version: '3.9'
services:
  docker_postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '15432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  docker_pgadmin:
    build:
      context: .
      dockerfile: ./dockerfile_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin123
    ports:
      - "5050:80"
    volumes:
        - ./servers.json:/pgadmin4/servers.json
volumes:
  db:
    driver: local
